// Generated by Wrangler on Tue Jun 25 2024 16:01:53 GMT+0200 (Central European Summer Time)
// by running `wrangler types functions/worker-configuration.d.ts`

interface Env {
    MAIN: KVNamespace;
    RESEND_API_KEY: string;
    EMAIL_SENDER_ADDRESS: string;
    EMAIL_RECIPIENT_ADDRESS: string;
}
