// Generated by Wrangler on Thu Jun 27 2024 22:26:32 GMT+0200 (Central European Summer Time)
// by running `wrangler types functions/worker-configuration.d.ts`

interface Env {
    MAIN: KVNamespace;
    RESEND_API_KEY: string;
    EMAIL_SENDER_ADDRESS: string;
    EMAIL_RECIPIENT_ADDRESS: string;
    ASSETS: Fetcher;
}
