version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORK_DIR: "/usr/src/ross.ch"
        PORT: 8080
    env_file:
      - .config.env
    image: ross.ch-webapp
    container_name: webapp
    restart: unless-stopped
    volumes:
      - web-root:/usr/src/ross.ch/public:rw,z
    networks:
      - default

  caddy:
    build:
        context: ./caddy
        dockerfile: Dockerfile
    restart: always
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /ross.ch/caddycerts:/etc/caddy/caddycerts:z,rw
      - web-root:/var/www/html:ro,z
    ports:
      - 80:80 # needed for Let's Encrypt
      - 443:443
    networks:
      - default
    env_file:
      - .config.env

  ghost:
    image: ghost:latest
    restart: unless-stopped
    env_file:
      - .config.env
    volumes:
      - /ross.ch/ghost_content:/var/lib/ghost/content:rw,z

volumes:
  web-root:

networks:
  default:
    driver: bridge