version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORK_DIR: "/usr/src/ross.ch"
        PORT: 8080
    env_file:
      - .config.env
    image: ross.ch-webapp
    container_name: webapp
    restart: unless-stopped
    volumes:
      - web-root:/usr/src/ross.ch/dist/public:rw,z
      - web-views:/usr/src/ross.ch/dist/src/views:rw,z
    networks:
      - default

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html:rw,z
      - ./nginx-conf:/etc/nginx/conf.d:rw,z
      - /ross.ch/certbot:/etc/letsencrypt:rw,z
      - certbot-var:/var/lib/letsencrypt:rw,z
      - /ross.ch/dhparam:/etc/ssl/certs:rw,z
    depends_on:
      - webapp
    networks:
      - default

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /ross.ch/certbot:/etc/letsencrypt:rw,z
      - certbot-var:/var/lib/letsencrypt:rw,z
      - web-root:/var/www/html:rw,z
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email hello@rchadwick.co.uk --agree-tos --no-eff-email --force-renewal -d ross.ch  -d www.ross.ch -d blog.ross.ch -d www.blog.ross.ch 

  ghost:
    image: ghost:alpine
    restart: unless-stopped
    env_file:
      - .config.env
    volumes:
      - /ross.ch/ghost_content:/var/lib/ghost/content:rw,z

volumes:
  web-views:
  web-root:
  certbot-var:

networks:
  default:
    driver: bridge