version: '3.7'

services:
  webapp:
    image: ghcr.io/chadsr/ross.ch:latest
    env_file:
      - .config.env
    environment:
      - REDIS_URL=redis://redis
    container_name: webapp
    labels:
      io.containers.autoupdate: registry
    restart: unless-stopped
    volumes:
      - web-root:/usr/src/ross.ch/dist/public:ro,z
    networks:
      - webapp

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - webapp

  caddy:
    build:
        context: ./caddy
        dockerfile: Dockerfile
    container_name: caddy
    labels:
      io.containers.autoupdate: registry
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - web-root:/var/www/html:ro,z
    ports:
      - 80:80
      - 443:443
    networks:
      - ghost
      - webapp
      - override

    env_file:
      - .config.env

  ghost:
    image: ghost:alpine
    container_name: ghost
    labels:
      io.containers.autoupdate: registry
    restart: unless-stopped
    env_file:
      - .config.env
    volumes:
      - /ross.ch/ghost_content:/var/lib/ghost/content:rw
    networks:
      - ghost

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 3600

volumes:
  web-root:
  caddy_data:
  caddy_config:

networks:
  ghost:
  webapp:
  override: