version: '3'

services:
  webapp:
    image: ghcr.io/chadsr/ross.ch:latest
    env_file:
      - .config.env
    container_name: webapp
    restart: unless-stopped
    volumes:
      - web-root:/usr/src/ross.ch/public:rw,z
    networks:
      - webapp

  caddy:
    build:
        context: ./caddy
        dockerfile: Dockerfile
    container_name: caddy
    restart: always
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - web-root:/var/www/html:ro,z
    ports:
      - 80:80 # needed for Let's Encrypt
      - 443:443
    networks:
      - ghost
      - webapp
      - override

    env_file:
      - .config.env

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    env_file:
      - .config.env
    volumes:
      - /ross.ch/ghost_content:/var/lib/ghost/content:rw,z
    networks:
      - ghost

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --interval 3600
volumes:
  web-root:
  caddy_data:
  caddy_config:

networks:
  ghost:
  webapp:
  override: