version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORK_DIR: "/usr/src/ross.ch"
        PORT: 8080
    env_file:
      - .config.env
    image: ross.ch-webapp
    container_name: webapp
    restart: unless-stopped
    volumes:
      - web-root:/usr/src/ross.ch/dist/public:rw,z
    networks:
      - default

  caddy:
    build:
        context: github.com/abiosoft/caddy-docker.git
        dockerfile: Dockerfile
        args:
          - plugins=git,cors,realip,expires,cache,cloudflare
          - enable_telemetry=false
    restart: always
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - /ross.ch/caddycerts:/etc/caddycerts:z,rw
      - web-root:/var/www/html:ro,z
    ports:
      - 80:80 # needed for Let's Encrypt
      - 443:443
    networks:
      - default
    env_file:
      - .config.env
    environment:
      CADDYPATH: "/etc/caddycerts"
      ACME_AGREE: "true"

  ghost:
    image: ghost:alpine
    restart: unless-stopped
    env_file:
      - .config.env
    volumes:
      - /ross.ch/ghost_content:/var/lib/ghost/content:rw,z

volumes:
  web-root:
  certbot-var:

networks:
  default:
    driver: bridge