version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORK_DIR: "/usr/src/ross.ch"
        PORT: 8080
    env_file:
      - .config.env
    image: ross.ch-webapp
    container_name: webapp
    restart: unless-stopped
    volumes:
      - web-root:/usr/src/ross.ch/dist/public
      - web-views:/usr/src/ross.ch/dist/src/views
    networks:
      - default

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html:Z
      - ./nginx-conf:/etc/nginx/conf.d:Z
      - /ross.ch/certbot:/etc/letsencrypt:Z
      - certbot-var:/var/lib/letsencrypt:Z
      - /ross.ch/dhparam:/etc/ssl/certs:Z
    depends_on:
      - webapp
    networks:
      - default

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /ross.ch/certbot:/etc/letsencrypt:Z
      - certbot-var:/var/lib/letsencrypt:Z
      - web-root:/var/www/html:Z
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email hello@rchadwick.co.uk --agree-tos --no-eff-email --force-renewal -d ross.ch  -d www.ross.ch -d blog.ross.ch -d www.blog.ross.ch 

    ghost:
      image: ghost:alpine
      restart: always
      depends_on:
        - db
      env_file:
        - .config.env
      environment:

      volumes:
        - /ross.ch/ghost_content:/var/lib/ghost/content

    db:
      image: postgres:alpine
      volumes:
        - /ross.ch/db-data:/var/lib/postgresql/data

volumes:
  web-views:
  web-root:
  certbot-var:

networks:
  default:
    driver: bridge