baseURL = 'https://ross.ch/'
languageCode = 'en-gb'
title = 'Ross Chadwick'
enableRobotsTXT = true

[taxonomies]
category = 'categories'
tag = 'tags'

[build]
noJSConfigInAssets = true
[build.buildStats]
enable = true

[module]
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = 'node_modules/@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2'
target = 'static/fonts/space-grotesk-latin-wght-normal.woff2'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'node_modules/@fortawesome/fontawesome-free/scss'
target = 'assets/scss/fontawesome'
