baseURL = 'https://ross.ch/'
languageCode = 'en-GB'
title = 'Ross Chadwick'
enableRobotsTXT = true
summaryLength = 10

[params]
dateFormat = "02 Jan 2006"
description = "Hacker, explorer, maker of strange things that are sometimes useful."
[params.author]
name = 'Ross Chadwick'

[outputs]
home = ['html', 'rss']
section = ['html']
taxonomy = ['html']
term = ['html']

[taxonomies]
category = 'categories'
tag = 'tags'

[languages]
[languages.en]
languageCode = 'en-GB'
languageName = 'English'
weight = 1
[languages.en.params]
reading_speed = 238

[build]
noJSConfigInAssets = true
[build.buildStats]
enable = true

[module]
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = 'node_modules/@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2'
target = 'static/fonts/space-grotesk-latin-wght-normal.woff2'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'node_modules/@fortawesome/fontawesome-free/scss'
target = 'assets/scss/fontawesome'
