name: Docker Image CI

on:
    release:
        types: [published]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
          -
            name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              images: |
                ghcr.io/chadsr/ross.ch
              tags: |
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=semver,pattern={{major}}
                type=sha
                latest
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build container image
            uses: docker/build-push-action@v3
            with:
                push: true
                platforms: linux/amd64
                tags: ${{ steps.meta.outputs.tags }}
                context: .
                build-args: |
                    WORK_DIR=/usr/src/ross.ch
                    PORT=8080
